POST http://localhost:3000/api/refresh-auth-tokens HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjBkODc3OTg4MDJlYWI4MGRmNDI4ZDQiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzEyMTYyNzU5LCJleHAiOjE3MTIyNDkxNTl9.0I2Zmh9iaq1pb1gmgrvGeXxDaka6WvTGl07uo4c0reo

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjBkODc3OTg4MDJlYWI4MGRmNDI4ZDQiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTcxMjE2MzI4MywiZXhwIjoxNzE0NzU1MjgzfQ.XAMLr046LIgs-UmeycnZ330pfdcmdWtphFxKx4orlV0",
    "email": "user@gmail.com",
    "password": "pass@Wo1r2",
    "confirm_password": "pass@Wo1r2",
    "name": "babatunde koiki"
}
